# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fintech-ingress
#   namespace: default
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: fintech-service
#             port:
#               number: 5000

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fintech-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fintech-service
                port:
                  number: 5000


